services:
  sequencer:
    build: .
    container_name: sequencer
    restart: unless-stopped
    ports:
      - "5174:5174"
    networks:
      - websequencer-net


networks:
  websequencer-net:
    external: true
    name: websequencer-net